# Generated by Django 5.2.6 on 2025-12-01 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0015_studentclasspoints_attendance_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(verbose_name='グループ番号')),
                ('group_name', models.CharField(blank=True, help_text='例: チーム虎、開発班A、など', max_length=100, verbose_name='グループ名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_masters', to='school_management.classroom', verbose_name='クラス')),
            ],
            options={
                'verbose_name': 'グループマスタ',
                'verbose_name_plural': 'グループマスタ',
                'unique_together': {('classroom', 'group_number')},
            },
        ),
        migrations.CreateModel(
            name='GroupMasterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, verbose_name='役割')),
                ('group_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='school_management.groupmaster', verbose_name='グループマスタ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_master_memberships', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': 'グループマスタメンバー',
                'verbose_name_plural': 'グループマスタメンバー',
                'unique_together': {('group_master', 'student')},
            },
        ),
    ]
