# Generated by Django 5.2.5 on 2026-02-20 05:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0016_groupmaster_groupmastermember'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(verbose_name='日報・今日やったこと')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lesson_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to='school_management.lessonsession', verbose_name='授業回')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '日報',
                'verbose_name_plural': '日報',
                'unique_together': {('lesson_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_comment', models.TextField(blank=True, verbose_name='学生コメント')),
                ('student_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='学生自己評価点')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='教師コメント')),
                ('teacher_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='教師評価点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to='school_management.classroom', verbose_name='クラス')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '自己評価',
                'verbose_name_plural': '自己評価',
                'unique_together': {('student', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.TextField(verbose_name='目標')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_goals', to='school_management.classroom', verbose_name='クラス')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生目標',
                'verbose_name_plural': '学生目標',
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
