# Generated by Django 4.2.2 on 2026-02-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0017_lessonreport_selfevaluation_studentgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grading_system',
            field=models.CharField(choices=[('standard', '通常評価（積み上げ）'), ('goal', '目標管理（講師評価）')], default='standard', max_length=20, verbose_name='評価システム'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_qr_linked',
            field=models.BooleanField(default=False, verbose_name='QR連携'),
        ),
    ]
