# Generated by Django 4.2.2 on 2026-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0018_classroom_grading_system_quiz_is_qr_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='qr_point_value',
            field=models.IntegerField(default=1, verbose_name='QRアクションポイント'),
        ),
    ]
