# Generated by Django 4.2.2 on 2026-02-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0019_classroom_qr_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='attendance_max_points',
            field=models.IntegerField(default=20, verbose_name='出席点満点'),
        ),
    ]
