# Generated by Django 4.2.2 on 2026-02-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0020_classroom_attendance_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluation',
            name='evaluator_group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='評価者グループ番号'),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='first_place_group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='1位グループ番号'),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='second_place_group_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='2位グループ番号'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='first_place_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_votes', to='school_management.group', verbose_name='1位グループ'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='second_place_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_votes', to='school_management.group', verbose_name='2位グループ'),
        ),
    ]
