# Generated by Django 4.2.2 on 2026-02-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0021_peerevaluation_evaluator_group_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='evaluator_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_evaluations_as_evaluator', to='school_management.group', verbose_name='評価者グループ'),
        ),
    ]
