# Generated by Django 5.2.5 on 2026-03-06 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0022_alter_peerevaluation_evaluator_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='attendance_max_points',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='出席点満点'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='qr_point_value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='QRアクションポイント'),
        ),
    ]
