# Generated by Django 5.2.5 on 2026-03-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0023_alter_classroom_attendance_max_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='evaluator_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_evaluations_as_evaluator', to='school_management.group', verbose_name='評価者グループ'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='first_place_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_place_votes', to='school_management.group', verbose_name='1位グループ'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='second_place_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_place_votes', to='school_management.group', verbose_name='2位グループ'),
        ),
    ]
