# Generated by Django 5.2.5 on 2026-04-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0024_alter_peerevaluation_evaluator_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grading_system',
            field=models.CharField(choices=[('default', 'デフォルト（通常）'), ('original', 'オリジナル（カスタマイズ）')], default='default', max_length=20, verbose_name='評価システム'),
        ),
        migrations.CreateModel(
            name='PointColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=100, verbose_name='項目名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_columns', to='school_management.classroom', verbose_name='クラス')),
            ],
            options={
                'verbose_name': '評価項目(列)',
                'verbose_name_plural': '評価項目(列)',
            },
        ),
    ]
