# Generated by Django 5.2.5 on 2026-04-02 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0024_alter_peerevaluation_evaluator_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, unique=True, verbose_name='セッションID')),
                ('email', models.EmailField(max_length=254, verbose_name='認証メールアドレス')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='有効期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Google OAuthセッション',
                'verbose_name_plural': 'Google OAuthセッション',
            },
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='提出メールアドレス'),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='提出学生'),
        ),
        migrations.AddConstraint(
            model_name='peerevaluation',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('lesson_session', 'student'), name='unique_peer_eval_per_student_per_session'),
        ),
    ]
