# Generated by Django 5.2.5 on 2026-04-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0025_alter_classroom_grading_system_pointcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentColumnScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school_management.pointcolumn', verbose_name='評価項目(列)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_scores', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '独自評価項目の得点',
                'verbose_name_plural': '独自評価項目の得点',
                'unique_together': {('column', 'student')},
            },
        ),
    ]
