# Generated by Django 5.2.5 on 2026-04-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0025_googleoauthsession_peerevaluation_email_and_more'),
        ('school_management', '0026_studentcolumnscore'),
    ]

    operations = [
    ]
