# Generated by Django 5.2.5 on 2026-04-04 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0027_merge_20260404_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodescan',
            name='point_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='school_management.pointcolumn', verbose_name='独自評価項目'),
        ),
    ]
