# Generated by Django 5.2.5 on 2026-04-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0028_qrcodescan_point_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grading_system',
            field=models.CharField(choices=[('default', 'デフォルト（通常）'), ('goal', '目標管理（講師評価）'), ('original', 'オリジナル（カスタマイズ）')], default='default', max_length=20, verbose_name='評価システム'),
        ),
    ]
