# Generated by Django 5.2.5 on 2026-04-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0030_auto_20260405_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='enable_comments',
            field=models.BooleanField(default=False, verbose_name='コメント機能有効'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='peer_evaluation_configured',
            field=models.BooleanField(default=False, verbose_name='ピア評価設定済み'),
        ),
    ]
