# Generated by Django 5.2.5 on 2026-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0031_lessonsession_enable_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsession',
            name='enable_feedback',
            field=models.BooleanField(default=False, verbose_name='感想欄有効'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='enable_group_evaluation',
            field=models.BooleanField(default=False, verbose_name='グループ評価有効'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='enable_member_evaluation',
            field=models.BooleanField(default=False, verbose_name='メンバー評価有効'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='group_ranking_count',
            field=models.IntegerField(default=2, verbose_name='グループ順位数'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='group_scores',
            field=models.JSONField(default=dict, help_text='例: {"1": 2, "2": 1}', verbose_name='グループ評価配点'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='member_ranking_count',
            field=models.IntegerField(default=2, verbose_name='メンバー順位数'),
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='member_scores',
            field=models.JSONField(default=dict, help_text='例: {"1": 2, "2": 1}', verbose_name='メンバー評価配点'),
        ),
    ]
