# Generated by Django 5.2.5 on 2026-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0032_lessonsession_enable_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluation',
            name='group_selections',
            field=models.JSONField(blank=True, default=dict, verbose_name='グループ選択（全ランク）'),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='member_selections',
            field=models.JSONField(blank=True, default=dict, verbose_name='メンバー選択（全ランク）'),
        ),
    ]
