# Generated by Django 5.2.5 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0035_peerevaluationsettings_group_evaluation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluationsettings',
            name='group_scores',
            field=models.JSONField(blank=True, default=list, help_text='例: [3, 2] → 1位3点, 2位2点', verbose_name='グループ評価配点'),
        ),
        migrations.AlterField(
            model_name='peerevaluationsettings',
            name='member_scores',
            field=models.JSONField(blank=True, default=list, help_text='例: [5, 3, 1] → 1位5点, 2位3点, 3位1点', verbose_name='メンバー評価配点'),
        ),
    ]

