# Generated by Django 5.2.5 on 2026-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_management', '0035_peerevaluationsettings_group_evaluation_method'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['student_number'], name='idx_customuser_student_number'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'student'), models.Q(('student_number', ''), _negated=True)), fields=('student_number',), name='unique_student_number_for_students'),
        ),
    ]
