# Generated by Django 5.2.5 on 2026-04-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0036_alter_peerevaluationsettings_member_scores_and_more'),
        ('school_management', '0036_customuser_idx_customuser_student_number_and_more'),
    ]

    operations = [
    ]
