# Generated by Django 5.2.5 on 2026-05-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0038_alter_lessonsession_has_peer_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsession',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='実施日'),
        ),
    ]
