# Generated by Django 5.2.5 on 2026-05-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0039_alter_lessonsession_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
    ]
