# Generated by Django 4.2.2 on 2026-06-15 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0039_alter_lessonsession_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonsession',
            options={'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True), 'session_number'], 'verbose_name': '授業回', 'verbose_name_plural': '授業回'},
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_student_number_for_students',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_students', to=settings.AUTH_USER_MODEL, verbose_name='担当教員'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'student'), models.Q(('student_number', ''), _negated=True)), fields=('student_number', 'managed_by'), name='unique_student_number_per_teacher'),
        ),
    ]
