# Generated by Django 4.2.2 on 2026-06-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0040_alter_lessonsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ['teacher', 'admin']), models.Q(('email__isnull', True), _negated=True)), fields=('email',), name='unique_email_for_teachers_and_admins'),
        ),
    ]
