# Generated by Django 5.2.5 on 2026-05-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0040_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
    ]
