# Generated by Django 4.2.2 on 2026-06-15 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0041_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_student_number_per_teacher',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_by',
            field=models.ManyToManyField(blank=True, related_name='managed_students', to=settings.AUTH_USER_MODEL, verbose_name='担当教員'),
        ),
    ]
