# Generated by Django 5.2.5 on 2026-06-22 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0042_remove_customuser_unique_student_number_per_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionChoice',
        ),
    ]
