# Generated by Django 5.2.5 on 2026-07-03 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_links(apps, schema_editor):
    """既存の ClassRoom.students / CustomUser.managed_by の中間テーブルを
    新しい ClassRoomEnrollment / TeacherStudentAssignment にコピーする（既存データを失わないため）"""
    ClassRoom = apps.get_model('school_management', 'ClassRoom')
    CustomUser = apps.get_model('school_management', 'CustomUser')
    ClassRoomEnrollment = apps.get_model('school_management', 'ClassRoomEnrollment')
    TeacherStudentAssignment = apps.get_model('school_management', 'TeacherStudentAssignment')

    for classroom in ClassRoom.objects.all():
        ClassRoomEnrollment.objects.bulk_create([
            ClassRoomEnrollment(classroom=classroom, student_id=student_id, is_active=True)
            for student_id in classroom.students.values_list('id', flat=True)
        ], ignore_conflicts=True)

    for student in CustomUser.objects.filter(role='student'):
        TeacherStudentAssignment.objects.bulk_create([
            TeacherStudentAssignment(teacher_id=teacher_id, student=student, is_active=True)
            for teacher_id in student.managed_by.values_list('id', flat=True)
        ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0045_normalize_zenkaku_student_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍中')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='在籍開始日時')),
                ('unlinked_at', models.DateTimeField(blank=True, null=True, verbose_name='除籍日時')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='school_management.classroom', verbose_name='クラス')),
                ('student', models.ForeignKey(limit_choices_to=models.Q(('role', 'student')), on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': 'クラス在籍',
                'verbose_name_plural': 'クラス在籍',
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TeacherStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='紐づけ日時')),
                ('unlinked_at', models.DateTimeField(blank=True, null=True, verbose_name='解除日時')),
                ('student', models.ForeignKey(limit_choices_to=models.Q(('role', 'student')), on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('teacher', models.ForeignKey(limit_choices_to=models.Q(('role__in', ['teacher', 'admin'])), on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL, verbose_name='教員')),
            ],
            options={
                'verbose_name': '担当教員割当',
                'verbose_name_plural': '担当教員割当',
                'unique_together': {('teacher', 'student')},
            },
        ),
        migrations.RunPython(copy_existing_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='managed_by',
        ),
    ]
