# Generated by Django 5.2.5 on 2026-07-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0046_remove_classroom_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
