# Generated by Django 5.2.5 on 2026-07-14 01:36

from django.db import migrations, models
from django.db.models import Count


def check_no_duplicate_student_numbers(apps, schema_editor):
    """
    このマイグレーションで学籍番号のユニーク制約を再追加する前に、
    既存データに重複がないか確認する。
    （過去のマイグレーションでこの制約が誤って削除されたままになっており、
    その間に重複登録されたデータが本番環境に残っている可能性があるため）

    重複が見つかった場合はマイグレーションを中断し、先に該当データを
    手動で確認・整理してから再実行してもらう。
    """
    CustomUser = apps.get_model('school_management', 'CustomUser')
    duplicates = (
        CustomUser.objects.filter(role='student')
        .exclude(student_number='')
        .values('student_number')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    if duplicates.exists():
        numbers = ', '.join(d['student_number'] for d in duplicates)
        raise RuntimeError(
            '学籍番号が重複している学生データが見つかったため、マイグレーションを中断しました。 '
            f'重複している学籍番号: {numbers} '
            '該当する学生データ（担当解除・完全削除・情報の統合など）を先に整理してから、'
            '再度マイグレーションを実行してください。'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_management', '0047_customuser_memo'),
    ]

    operations = [
        migrations.RunPython(check_no_duplicate_student_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'student'), models.Q(('student_number', ''), _negated=True)), fields=('student_number',), name='unique_student_number_for_students'),
        ),
    ]
