from .admin_teacher_dashboard import admin_teacher_management
from .dashboard_view import dashboard_view
from .student_dashboard import student_dashboard
from .teacher_dashboard import teacher_dashboard